# Upload ZIP archives of datasets to GitHub Releases

name: Upload ZIP archives

# Only run for releases
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    name: Upload ZIP archives
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Create a UTF8 ZIP archive
      run: |
        # create the tarball
        mkdir china-geospatial-data-UTF8
        cp *.gmt *.md china-geospatial-data-UTF8/
        zip -r china-geospatial-data-UTF8.zip china-geospatial-data-UTF8

    - name: Create a GB2312 ZIP archive
      run: |
        mkdir china-geospatial-data-GB2312
        cp *.md china-geospatial-data-GB2312/
        for data in $(ls -1 *.gmt); do
          iconv -f UTF-8 -t GB2312 ${data} > china-geospatial-data-GB2312/${data}
        done
        zip -r china-geospatial-data-GB2312.zip china-geospatial-data-GB2312

    - name: Upload as release assets
      run: gh release upload ${{ github.ref_name }} china-geospatial-data-*.zip
      env:
        GH_TOKEN: ${{ github.token }}
